name: Auto Docker Build and Release

on:
  push:
    branches: [ main, master ]
    paths:
      - 'frontend/package.json'
      - 'frontend/src/**'
      - 'web_app.py'
      - 'storage.py'
      - 'scheduler.py'
      - 'notify.py'
      - 'utils.py'

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/baidu-autosave

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Extract version from package.json
        id: get-version
        run: |
          VERSION=$(jq -r '.version' frontend/package.json)
          echo "Version from package.json: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Check if version changed
        id: check-version
        run: |
          git fetch origin
          
          # 检查前一个提交是否存在frontend/package.json
          if git show HEAD~1:frontend/package.json >/dev/null 2>&1; then
            PREVIOUS_VERSION=$(git show HEAD~1:frontend/package.json | jq -r '.version')
          else
            PREVIOUS_VERSION="0.0.0"
            echo "Previous commit doesn't have frontend/package.json, treating as first build"
          fi
          
          CURRENT_VERSION=$(jq -r '.version' frontend/package.json)
          echo "Previous version: $PREVIOUS_VERSION"
          echo "Current version: $CURRENT_VERSION"
          
          if [ "$PREVIOUS_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
            echo "should_build=true" >> $GITHUB_OUTPUT
          else
            echo "No version change detected"
            echo "should_build=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: steps.check-version.outputs.should_build == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        if: steps.check-version.outputs.should_build == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Log in to Docker Hub
        if: steps.check-version.outputs.should_build == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker tags
        if: steps.check-version.outputs.should_build == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=v${{ env.VERSION }}
            type=raw,value=latest

      - name: Build and push Docker image
        if: steps.check-version.outputs.should_build == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Create Release
        if: steps.check-version.outputs.should_build == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }} 